export const dialectConfigs = {
  mysql: {
    name: "MySQL",
    dataTypes: {
      "VARCHAR(50)": "text",
      "VARCHAR(100)": "text",
      "VARCHAR(255)": "text",
      TEXT: "longtext",
      LONGTEXT: "longtext",
      INT: "number",
      BIGINT: "number",
      TINYINT: "number",
      SMALLINT: "number",
      "DECIMAL(10,2)": "decimal",
      FLOAT: "decimal",
      DOUBLE: "decimal",
      DATE: "date",
      DATETIME: "datetime",
      TIMESTAMP: "datetime",
      BOOLEAN: "boolean",
      "TINYINT(1)": "boolean",
    },
    keywords: [
      "SELECT",
      "FROM",
      "WHERE",
      "INSERT",
      "UPDATE",
      "DELETE",
      "CREATE",
      "DROP",
      "ALTER",
      "INDEX",
      "LIMIT",
      "ORDER BY",
      "GROUP BY",
      "HAVING",
      "JOIN",
      "LEFT JOIN",
      "RIGHT JOIN",
      "INNER JOIN",
      "OUTER JOIN",
      "UNION",
      "DISTINCT",
      "COUNT",
      "SUM",
      "AVG",
      "MAX",
      "MIN",
      "AND",
      "OR",
      "NOT",
      "IN",
      "LIKE",
      "BETWEEN",
      "IS NULL",
      "IS NOT NULL",
    ],
    functions: [
      "COUNT(*)",
      "SUM()",
      "AVG()",
      "MAX()",
      "MIN()",
      "NOW()",
      "CURDATE()",
      "YEAR()",
      "MONTH()",
      "DAY()",
      "CONCAT()",
      "LENGTH()",
      "UPPER()",
      "LOWER()",
      "TRIM()",
    ],
  },
  postgresql: {
    name: "PostgreSQL",
    dataTypes: {
      "VARCHAR(50)": "text",
      "VARCHAR(100)": "text",
      "VARCHAR(255)": "text",
      TEXT: "longtext",
      INTEGER: "number",
      BIGINT: "number",
      SMALLINT: "number",
      "NUMERIC(10,2)": "decimal",
      REAL: "decimal",
      "DOUBLE PRECISION": "decimal",
      DATE: "date",
      TIMESTAMP: "datetime",
      TIMESTAMPTZ: "datetime",
      BOOLEAN: "boolean",
      SERIAL: "number",
      BIGSERIAL: "number",
    },
    keywords: [
      "SELECT",
      "FROM",
      "WHERE",
      "INSERT",
      "UPDATE",
      "DELETE",
      "CREATE",
      "DROP",
      "ALTER",
      "INDEX",
      "LIMIT",
      "OFFSET",
      "ORDER BY",
      "GROUP BY",
      "HAVING",
      "JOIN",
      "LEFT JOIN",
      "RIGHT JOIN",
      "INNER JOIN",
      "FULL OUTER JOIN",
      "UNION",
      "DISTINCT",
      "COUNT",
      "SUM",
      "AVG",
      "MAX",
      "MIN",
      "AND",
      "OR",
      "NOT",
      "IN",
      "LIKE",
      "ILIKE",
      "BETWEEN",
      "IS NULL",
      "IS NOT NULL",
      "CASE",
      "WHEN",
      "THEN",
      "ELSE",
      "END",
    ],
    functions: [
      "COUNT(*)",
      "SUM()",
      "AVG()",
      "MAX()",
      "MIN()",
      "NOW()",
      "CURRENT_DATE",
      "EXTRACT()",
      "DATE_PART()",
      "CONCAT()",
      "LENGTH()",
      "UPPER()",
      "LOWER()",
      "TRIM()",
      "COALESCE()",
    ],
  },
}

export const dataPatterns = {
  first_name: ["John", "Jane", "Michael", "Sarah", "David", "Emily", "Robert", "Lisa", "James", "Maria"],
  last_name: ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis"],
  full_name: ["John Smith", "Jane Doe", "Michael Johnson", "Sarah Williams", "David Brown"],
  email_domains: ["gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "company.com"],
  companies: ["TechCorp Inc", "Global Solutions", "Innovate Systems", "Digital Dynamics"],
  cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia"],
  statuses: ["Active", "Inactive", "Pending", "Completed", "In Progress"],
  descriptions: [
    "High-quality product with excellent features.",
    "Innovative solution for modern requirements.",
    "User-friendly interface with powerful functionality.",
    "Cost-effective option with great value.",
  ],
}

export const constraintTypes = ["PRIMARY KEY", "NOT NULL", "UNIQUE", "FOREIGN KEY", "CHECK"]
